### PR TITLE
New enhancements for consistent screenshots

### PR DESCRIPTION
**Pull request by MingDai**
Cleaned up puppeteer to be more reliable. The bulk of the bottleneck is now on one line of waiting for page to fully load (line 74)

Cleaned up auto_screenshot command output puppeteer error logs and also make sure there is never a  Image File = None in the database. 

Changed deployment configurations to demand more CPU 

added a Bash script that does all the deployment commands all together. Docker build, Docker push, Helm upgrade

### CODE REVIEW

**Comment by indirectlylit** [comment]
hey, thanks for the PR!

Mind targeting to the Learning Equality repo?

**Comment by MingDai** [comment]
Sure thing. Done!

**Comment by indirectlylit** [comment]
thanks - closing this copy

**Comment by indirectlylit** [comment]
moved to https://github.com/learningequality/health-inspector/pull/13

**Pull request closed without merging**
